version: '3'

services:
  description:
    build: description/
    depends_on:
      - 'database'
    ports: 
      - '3001:3001'

  expanded:
    build: expanded_description/
    depends_on:
      - 'database'
    ports:
      - '3005:3005'
  
  feedback:
    build: feedback/
    depends_on:
      - 'database'
    ports:
      - '3002:3002'

  proxy:
    build: proxy/
    depends_on:
      - 'description'
      - 'expanded'
      - 'feedback'
    ports:
      - '3000:3000'

  database:
    image: mongo:latest